### ISSUE TITLE
 java.lang.NoSuchFieldError: No static field Theme_FullScreenDialog of type

### ISSUE THREAD

**Issue by caiyonglong** [kezong/fat-aar-android#161]
问题描述：
使用fat-aar合并多个react-native所需要的aar包，然后引入新的工程，app运行时报错，根据日志描述，是Theme未找到

## 分析：
RN运行时，设置了原生的一个主题，但是在R文件中没有找到这个主题声明，然后就崩溃了。

```
Process:xxxxx, PID: 9329
    java.lang.NoSuchFieldError: No static field Theme_FullScreenDialog of type I in class Lcom/facebook/react/R$style; or its superclasses (declaration of 'com.facebook.react.R$style' appears in /data/app/com.xxxx-i7-01ZpO84Qhw1x9vcYnCg==/base.apk)
        at com.facebook.react.views.modal.ReactModalHostView.showOrUpdate(ReactModalHostView.java:226)
        at com.facebook.react.views.modal.ReactModalHostManager.onAfterUpdateTransaction(ReactModalHostManager.java:101)
        at com.facebook.react.views.modal.ReactModalHostManager.onAfterUpdateTransaction(ReactModalHostManager.java:24)
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:50)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:278)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:179)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:972)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:943)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
        at android.view.Choreographer.doCallbacks(Choreographer.java:865)
        at android.view.Choreographer.doFrame(Choreographer.java:796)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

查看ReactNative源码，确实是使用到了Theme_FullScreenDialog这个主题。但是因为合包后的R文件找不到（r-classes.jar中R.class），这个Theme_FullScreenDialog定义，导致崩溃。

## 疑问点：
Theme_FullScreenDialog这个主题文件应该是属于Android原生的，并不属于React Native内新定义的主题文件。
使用fat-aar合包生成的aar文件，values.xml里面有这个Theme_FullScreenDialog定义。但是在r-classes.jar中R.class里面又没有该主题的声明，编译时能正常运行，但是运行时就崩了。

请教大佬，这个是aar插件的问题，还是其他的问题，能解决吗？

**Comment by caiyonglong** [comment]
已找出问题，插件中的R.class文件生成逻辑有问题。

**Comment by kezong** [comment]
@caiyonglong 如果确认问题的话，希望可以pull request提供一下你的思路。

**Comment by caiyonglong** [comment]
嗯，好的

**Comment by caiyonglong** [comment]
从插件里面的R.class生成逻辑看。
先读取 R-def.txt文件中的每个主题样式，然后保存到symbolsMap中。
然后在读取R.txt文件中的资源定义，和symbolsMap中的对比。
如下：

```
if (symbolsMap.containsKey(subclass) && symbolsMap.get(subclass).containsKey(name)) {
                    rMap[subclass].putAt(name, type)
}
```

但是，在aar包的 R-def.txt的值，有些主题的值是Theme.FullScreenDialog。这种以"."分割，而在R.txt中是以“_”链接。
所有在上需判断条件中是，这种包含"."的主题样式并不会生成到最终的R.class文件中。

所以现在解决方式是
第一种是读取R-def.txt时，将“.”替换成“_”
第二种是不要这个if判断（我理解是这个if条件是可以减少不必要的主题，从而减少R文件大小）
