### ISSUE TITLE
ClassNotFoundException: Didn't find class .. on path

### ISSUE THREAD

**Issue by ravpod** [kezong/fat-aar-android#203]
I've created my own library with other dependencies but even thought they are marked as embed I've errors like below:
```
E/AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/isseiaoki/simplecropview/R$styleable;
        at com.isseiaoki.simplecropview.CropImageView.handleStyleable(CropImageView.java:316)
        at com.isseiaoki.simplecropview.CropImageView.<init>(CropImageView.java:187)
        at com.isseiaoki.simplecropview.CropImageView.<init>(CropImageView.java:154)
        	... 28 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.isseiaoki.simplecropview.R$styleable" on path: DexPathList[[zip file "/data/app/com.example.myapplication-AbhUXn25mQt7bodq6Mw68Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.myapplication-AbhUXn25mQt7bodq6Mw68Q==/lib/x86, /data/app/com.example.myapplication-AbhUXn25mQt7bodq6Mw68Q==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 31 more
```

**Comment by kezong** [comment]
Try to upgrade plugin to latest version
