### ISSUE TITLE
请问支持dataBinding吗？用了 databinding的 module 合并成功之后 ，运行报错！

### ISSUE THREAD

**Issue by keke521** [kezong/fat-aar-android#25]
gradle 3.4.1
com.kezong:fat-aar:1.1.7

**Comment by kezong** [comment]
dataBinding没有额外适配过，可以提供下更详细的错误信息。

**Comment by keke521** [comment]
![image](https://user-images.githubusercontent.com/24793262/61042335-977fb980-a406-11e9-8ec0-a9bac0c6f6c4.png)

2019-07-11 18:03:46.613 16671-16671/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.keke.testfat_aar, PID: 16671
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.keke.testfat_aar/com.keke.lib1.example.Lib1Activity}: java.lang.NullPointerException: Attempt to read from field 'android.widget.TextView com.keke.lib1.databinding.ActivityLib1Binding.text' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2747)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6360)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'android.widget.TextView com.keke.lib1.databinding.ActivityLib1Binding.text' on a null object reference
        at com.keke.lib1.example.Lib1Activity.onCreate(Lib1Activity.java:18)
        at android.app.Activity.performCreate(Activity.java:6863)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2700)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.app.ActivityThread.main(ActivityThread.java:6360) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770) 

就是会报 空指针 binding 为空

**Comment by keke521** [comment]
项目是 mvvm架构， 布局都是databinding，作者如果能适配，简直太感谢了

**Comment by kezong** [comment]
晚上抽时间看了一下，因为插件资源合并的方案和dataBinding的实现有冲突，现在只支持在主module中使用dataBinding，也就是apply plugin: fat-aar的那一个module。
如果要支持在子module中支持dataBinding，比较困难，短时间内无法实现。

**Comment by keke521** [comment]
咨询下，这个databinding支持，有计划做吗😊

**Comment by kezong** [comment]
@keke521 暂时没有计划。
你也可以看看有没有其他的解决方案，如果有什么好的解决方案可以同步给我。
同时你可以基于我的源码来实现databinding合并的能力，欢迎pull request.
