### ISSUE TITLE
SAXNotRecognizedException 

### ISSUE THREAD

**Issue by SusionSuc** [kezong/fat-aar-android#252]
Resource and asset merger: unrecognized feature http://xml.org/sax/features/external-general-entities
    org.xml.sax.SAXNotRecognizedException: unrecognized feature http://xml.org/sax/features/external-general-entities
        at org.gjt.xpp.sax2.Driver.setFeature(Driver.java:178)
        at com.android.utils.XmlUtils.createSaxParser(XmlUtils.java:639)
        at com.android.utils.PositionXmlParser.parseInternal(PositionXmlParser.java:249)
        at com.android.utils.PositionXmlParser.parseInternal(PositionXmlParser.java:201)
        at com.android.utils.PositionXmlParser.parse(PositionXmlParser.java:148)
        at com.android.utils.PositionXmlParser.parse(PositionXmlParser.java:80)
        at com.android.utils.PositionXmlParser.parse(PositionXmlParser.java:111)
        at com.android.ide.common.resources.ValueResourceParser2.parseDocument(ValueResourceParser2.java:212)
        at com.android.ide.common.resources.ValueResourceParser2.parseFile(ValueResourceParser2.java:91)
        at com.android.ide.common.resources.ResourceSet.createResourceFile(ResourceSet.java:560)
        at com.android.ide.common.resources.ResourceSet.parseFolder(ResourceSet.java:491)

**Build Environment**
 - Operating System: [MacOS]
 - Gradle Plugin Version: [4.1.0]
 - Gradle Version: [ 6.5]
 - Fat-aar Version: [1.3.3]

**Comment by kezong** [comment]
这个问题有更多的信息吗？你是不是本地已经解决了

**Comment by SusionSuc** [comment]
这个解决了

**Comment by fanturbo** [comment]
> 这个解决了
咋解决的啊
