### ISSUE TITLE
Could not generate a decorated class for type FatAarPlugin (no LibraryVariant class found)

### ISSUE THREAD

**Issue by konsoletyper** [kezong/fat-aar-android#310]
**Describe the issue**

I added plugin to the existing project according to the readme and get following error while trying to build the project:

```
* What went wrong:
A problem occurred evaluating project ':****'.
> Failed to apply plugin 'com.kezong.fat-aar'.
   > Could not create plugin of type 'FatAarPlugin'.
      > Could not generate a decorated class for type FatAarPlugin.
         > com/android/build/gradle/api/LibraryVariant
```

Stacktrace adds some explanation (but it's still unclear how to solve the problem):

```
Caused by: java.lang.NoClassDefFoundError: com/android/build/gradle/api/LibraryVariant
        at org.gradle.internal.reflect.ClassInspector.inspectClass(ClassInspector.java:70)
        at org.gradle.internal.reflect.ClassInspector.visitGraph(ClassInspector.java:56)
        at org.gradle.internal.reflect.ClassInspector.inspect(ClassInspector.java:36)
        at org.gradle.internal.instantiation.generator.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:264)
        at org.gradle.internal.instantiation.generator.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:208)
        ... 161 more
Caused by: java.lang.ClassNotFoundException: com.android.build.gradle.api.LibraryVariant
        ... 166 more
```

**Build Environment**
 - Operating System: Fedora
 - Gradle Plugin Version: 4.1.2 (not sure)
 - Gradle Version: 6.6
 - Fat-aar Version: 1.3.6

**NOTE**: I'm not an Android developer and don't know how Android plugin version is specified. Found following across huge build scripts and hope it's the one you need:

```groovy
dependencies {
  classpath 'com.android.tools.build:gradle:4.1.2'
}
```

**Comment by konsoletyper** [comment]
Can I get some attention to this issue?
