### ISSUE TITLE
子lib module中依赖多个aar文件，有的aar文件带so库，有的不带，当不带so库的aar在程序运行后执行它内部的native方法，程序就会崩溃【已解决，可以关闭该issue了】

### ISSUE THREAD

**Issue by jackom** [kezong/fat-aar-android#81]
子lib module中依赖多个aar文件，有的aar文件带so库，有的不带，当不带so库的aar在程序运行后执行它内部的native方法，程序就会崩溃。报错信息大致如下：

`    java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.ss.sys.ces.a.h() (tried Java_com_ss_sys_ces_a_h and Java_com_ss_sys_ces_a_h__)
        at com.ss.sys.ces.a.h(Native Method)
        at com.ss.sys.ces.Perception.pullSg(Unknown Source:0)
        at com.ss.sys.ces.b.pullSg(Unknown Source:0)`

**Comment by jackom** [comment]
我尝试在子lib 的module中配置jniLibs，然后再在它的build.gradle中配置如下代码：
`	repositories {
		flatDir {
			dirs 'libs'
		}
	}

	packagingOptions {
//		exclude 'lib/x86/*.so'
		exclude 'lib/x86_64/*.so'
//		exclude 'lib/armeabi/*.so'
		exclude 'lib/arm64-v8a/*.so'
		exclude 'lib/armeabi-v7a/*.so'
		exclude 'lib/mips/*.so'
		exclude 'lib/mips64/*.so'
	}`

然后再在主module中的build.gradle中配置：
`        ndk {
            abiFilters  "armeabi", "x86"  // 指定要ndk需要兼容的架构
        }`

初步猜测是 子lib的module中依赖的某个不带so库的aar文件，在调用它里面的方法的时候，代码不断跳转，执行到了它里面的native方法，然后系统会去找 jniLibs目录下有没有对应的so库，但是没找到，所以就会导致应用崩溃。但是如果去掉  jniLibs目录，那样就不会报错，但是由于其他带so库的aar文件需要用到so文件，所以目前不能去掉  jniLibs目录。 如何让在保留  jniLibs目录也配置CPU架构的情况下，不带so库的aar文件(第三方aar文件，没有提供so库)在执行到它内部的native方法也能成功？

**Comment by jackom** [comment]
已经解决了，我项目里面只配置了"armeabi", "x86" 这两个架构，然后我看了那个提供第三方aar的官方文档，它里面指出他们的 SDK中使用的so文件支持四种架构：x86,x86_64,armeabi-v7a,arm64-v8a，后面我多加了一个 armeabi-v7a架构，也设置成： "armeabi", "armeabi-v7a", "x86"  就没问题了。
