### ISSUE TITLE
Gradle 6 compatibility

### ISSUE THREAD

**Issue by llDavidll** [kezong/fat-aar-android#97]
Hi,

It seems this plugin is not compatible with Gradle 6.

My project works fine using Gradle 5.6.4, and fails to build with Gradle 6.0.1 (and 6.0).

This is the relevant part of the stacktrace:

```
groovy.lang.MissingMethodException: No signature of method: org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.DefaultArtifactSet$$Lambda$102/1069381811.getDependencies() is applicable for argument types: () values: []
Possible solutions: visitDependencies(org.gradle.api.internal.tasks.TaskDependencyResolveContext)
	at com.kezong.fataar.VariantProcessor.processArtifacts(VariantProcessor.groovy:119)
	at com.kezong.fataar.VariantProcessor.processVariant(VariantProcessor.groovy:88)
	at com.kezong.fataar.VariantProcessor$processVariant$1.call(Unknown Source)
	at com.kezong.fataar.FatLibraryPlugin.processVariant(FatLibraryPlugin.groovy:94)
	at org.gradle.internal.metaobject.BeanDynamicObject$GroovyObjectAdapter.invokeOpaqueMethod(BeanDynamicObject.java:583)
```

**Comment by kezong** [comment]
Thanks for the feedback.
I has adapted it in 1.2.8.

**Comment by phocea13** [comment]
Running into a similar issue in a context where I don't control the artifact repo. Do you have a but more info on what "adapted" means so I can send the proper instructions to the team managing the repo?
